repos:
  - repo: local
    hooks:
      - id: poetry-lock
        name: poetry-lock
        entry: bash -c 'poetry lock --no-update'
        language: system
        files: poetry.lock

  - repo: local
    hooks:
      - id: poetry-export
        name: poetry-export
        entry: bash -c 'poetry export -f requirements.txt -o requirements.txt --without-hashes'
        language: system
        files: requirements.txt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]
